### ISSUE TITLE
No "scripts" in package.json and no node_modules after "npm install"

### ISSUE THREAD

**Issue by rushuifang** [Nllai/Lab-project1#1]
There's no "script" in package.json that allows "npm start" run. Also, when I run "npm install", there won't be any node_modules installed.

**Comment by HsiaoTienFan** [comment]
I couldn't replicate the `npm install` problem. When I ran it the node_modules folder was installed.

I've updated the package.json file and the server should start now.

**Comment by rushuifang** [comment]
The updated **package.json** works fine now. I think *npm install* problem also goes away because of other properties in the **package.json** are added.
